databases:
  - name: task_manager
    databaseName: task_manager
    user: task_manager

services:
  - type: web
    name: task_manager
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn task_manager.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4