# Generated by Django 4.2.7 on 2023-11-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
