# Generated by Django 4.2.6 on 2023-11-02 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            'statuses',
            '0002_alter_status_options_alter_status_created_at_and_more'
        ),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='author',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(
                blank=True,
                max_length=10000,
                verbose_name='Описание'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='executor',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Исполнитель'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(
                max_length=150,
                unique=True,
                verbose_name='Имя'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='statuses',
                to='statuses.status',
                verbose_name='Статус'
            ),
        ),
    ]
